In [2]:
import torch
from IPython import display
from matplotlib import pyplot as plt
import numpy as np
import random

In [4]:
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [7]:
import torch.utils.data as Data

batch_size = 10
dataset = Data.TensorDataset(features, labels)
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)

In [8]:
for X, y in data_iter:
    print(X,y)
    break

tensor([[-1.0985, -0.2662],
        [-1.3495, -2.2201],
        [ 3.0673, -0.5771],
        [ 0.5046,  1.0602],
        [ 1.0053, -2.2473],
        [-1.3209, -0.6956],
        [ 0.1422,  0.2300],
        [-0.6091, -1.3211],
        [-0.2928, -1.7036],
        [ 1.7040, -1.2766]]) tensor([ 2.9002,  9.0470, 12.2820,  1.6044, 13.8709,  3.9100,  3.6759,  7.4731,
         9.4083, 11.9263])


In [9]:
import torch.nn as nn

In [17]:
class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1, bias=True)
    def forward(self, x):
        y = self.linear(x)
        return y

In [18]:
net = LinearNet(num_inputs)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [19]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[0.5022, 0.4827]], requires_grad=True)
Parameter containing:
tensor([0.4625], requires_grad=True)


In [23]:
from torch.nn import init
init.normal_(net.linear.weight, mean=0, std=0.01)
init.constant_(net.linear.bias, val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [24]:
loss = nn.MSELoss()

In [25]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [26]:
num_epochs = 3
for epoch in range(1, num_epochs+1):
    for X,y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))

epoch 1, loss: 0.000509
epoch 2, loss: 0.000141
epoch 3, loss: 0.000032


In [27]:
dense = net.linear
print(true_w, dense.weight)
print(true_b, dense.bias)

[2, -3.4] Parameter containing:
tensor([[ 2.0006, -3.3993]], requires_grad=True)
4.2 Parameter containing:
tensor([4.1990], requires_grad=True)
